version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: coordinadora-mysql-v3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coordinadora
      MYSQL_USER: coordinadora
      MYSQL_PASSWORD: coordinadora
    volumes:
      - ./MySQL/coordinadora_DLL.sql:/docker-entrypoint-initdb.d/coordinadora_DLL.sql
      - ./MySQL/Dump_DML.sql:/docker-entrypoint-initdb.d/Dump_DML.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coordinadora-nodejs-v3
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
